// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCAqUpnlSvPAKJRqtf5BfhyPmam6CKi_I',
    appId: '1:270381856958:android:a079db12823ec80ad3c6ef',
    messagingSenderId: '270381856958',
    projectId: 'petpal-8c1c4',
    storageBucket: 'petpal-8c1c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqjoJjPozHWoYErmZEFDcW7W98bywM4F8',
    appId: '1:270381856958:ios:c86b09b3b7e6b28bd3c6ef',
    messagingSenderId: '270381856958',
    projectId: 'petpal-8c1c4',
    storageBucket: 'petpal-8c1c4.firebasestorage.app',
    iosBundleId: 'com.example.mybestfriend',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAktTV6yLbctorUxsFOZD5qPNd8HhmdhyM',
    appId: '1:270381856958:web:11944f8ac6e07f73d3c6ef',
    messagingSenderId: '270381856958',
    projectId: 'petpal-8c1c4',
    authDomain: 'petpal-8c1c4.firebaseapp.com',
    storageBucket: 'petpal-8c1c4.firebasestorage.app',
    measurementId: 'G-VGBCNZH5PC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqjoJjPozHWoYErmZEFDcW7W98bywM4F8',
    appId: '1:270381856958:ios:c86b09b3b7e6b28bd3c6ef',
    messagingSenderId: '270381856958',
    projectId: 'petpal-8c1c4',
    storageBucket: 'petpal-8c1c4.firebasestorage.app',
    iosBundleId: 'com.example.mybestfriend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAktTV6yLbctorUxsFOZD5qPNd8HhmdhyM',
    appId: '1:270381856958:web:2dd13bf92dacd37dd3c6ef',
    messagingSenderId: '270381856958',
    projectId: 'petpal-8c1c4',
    authDomain: 'petpal-8c1c4.firebaseapp.com',
    storageBucket: 'petpal-8c1c4.firebasestorage.app',
    measurementId: 'G-RYJ7B550D7',
  );

}